### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by natiz** [jpillora/jquery.rest#1]
Hey there!

I'd really love some OAuth support for this library.
Consider using this OAuth library: http://oauth.googlecode.com/svn/code/javascript/oauth.js

Thanks!

**Comment by jpillora** [comment]
Hey Kitt0s

I'm abit wary about the file size increase, though I'll look into it tonight

**Comment by jpillora** [comment]
Hey Kitt0s,

OAuth 1.0 in JavaScript (the library you linked) is insecure in the browser as the application's secret key is required to make requests, OAuth 2.0 is more suitable and was designed with the intention of use in the browser. So I may add OAuth 2 support if enough people need it.

If you really really want OAuth 1 support and can accept the security issues, include this file https://gist.github.com/andyedinborough/1012960 and change the `$.ajax` to `$.oauth` in jquery.rest.js (untested though it should work :blush:)
