### ISSUE TITLE
http: missing from one of links in documentation.

### ISSUE THREAD

**Issue by halso** [jpillora/jquery.rest#12]
On the documentation page at :-
https://github.com/jpillora/jquery.rest
just after:-

First setup your page:

The code includes:-

<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

which is missing the http: and so should read:-

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js">\</script>

Nice script.  Thanks.

Steve.

**Comment by jpillora** [comment]
Thanks for heads up, though have you tested it :P ?

**Comment by jpillora** [comment]
It's actually on purpose, essentially, it tells the browser (even IE6), to use the protcol of the _current page_. For more on this, read [this article](http://encosia.com/cripple-the-google-cdns-caching-with-a-single-character/).
