### ISSUE TITLE
Bloqueado carregamento de conteúdo ativo mesclado

### ISSUE THREAD

**Issue by valmirphp** [jpillora/jquery.rest#15]
Estou com um problema, quando uso a api ela funcionando perfeitamente, porem de uns dias para ca, com atualização do mozila firefox.
Esta dando erro quando acessado a api via Firefox, no console apresenta o seguinte erro: Bloqueado carregamento de conteúdo ativo mesclado

Você ja passou por isso?
Aproveitando para agradecer por essa lib, que realmente deixa muito pratico e legível as requisição ajax. Parabéns!

**Comment by jpillora** [comment]
Fico feliz a sua utilidade para você ! Conteúdo misto normalmente significa
que seus arquivos estáticos estão sendo servidos a partir de HTTP e HTTPS,
se isso é verdade , você vai precisar para assegurar que todos os arquivos
( e API) está usando HTTPS

**Comment by valmirphp** [comment]
Faz todo sentido, pois minha api esta em https, porem o serviço que estou
comsumindo com ajax, esta em um servidor HTPP

Acho que vc descobriu o problema meu muito obrigado

Em 31 de agosto de 2013 20:47, Jaime Pillora notifications@github.comescreveu:

**Comment by jpillora** [comment]
não há problema
