### ISSUE TITLE
Add ability to specify transport for rest client

### ISSUE THREAD

**Issue by stalniy** [jpillora/jquery.rest#16]
It's useful to have an option which is responsible for `transport` functionality (`backend`, `responder`) - currently there is hard-coded `$.ajax`. Having such option it would be easier to test functionality which depends on rest schema by substitution its responder (e.g. localStorage, or just plain js responder). Responder handles request and can respond to it like a normal backend.

Example:

``` js
require(['rest-schema', 'lib/rest_localbackend'], function (schema, LocalBackend) {
  schema.add('todos', { backend: LocalBackend.respond });
});
```

It gives an ability to work with `todos` list only on frontend (a good way to stub the server if server functionality is still not ready for integration).

**Comment by jpillora** [comment]
Yup I can add this, so long as a drop in replacement for the `$.ajax` function is enough? Note, each REST verb returns the `response` promise that `$.ajax` returns.

**Comment by stalniy** [comment]
Yes, it's ok. You just need to document which parameters are passed into `responder` and that it should return promise. Thanks!
