### ISSUE TITLE
what does ' (polyfill required not non-webkit)' mean ?

### ISSUE THREAD

**Issue by ms7285-gmail-com** [jpillora/jquery.rest#24]
This looks like  a great tool but . . .
what does ' (polyfill required not non-webkit)' mean ?

**Comment by jpillora** [comment]
https://github.com/jpillora/jquery.rest#basic-authentication this section is more clear I think

**Comment by ms7285-gmail-com** [comment]
That expansion helps but not the words ' not non-webkit' !

Do you mean that only webkit doesn't require a a polyfill  ?
Perhaps something like ::
     as of 2014-02-28 only webkit supports this directly; the others 
need a polyfil of
