### ISSUE TITLE
Content-Type header

### ISSUE THREAD

**Issue by gamefundas** [jpillora/jquery.rest#32]
Is there a way to set the Content Type header to requests? I couldn't figure out from the examples or the documentation.

**Comment by jpillora** [comment]
Use the Ajax option when creating a resource (or verb)

https://github.com/jpillora/jquery.rest/blob/gh-pages/README.md#ajax

Then inside that use a headers object

**Comment by jpillora** [comment]
So I just tested this:

``` js
client.add("bar", { ajax: { headers: { 'content-type': 'foo/text' } } })
```

Then all requests under the `bar` resource will use `content-type` = `foo/text`
