### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by antoncl** [jpillora/jquery.rest#33]
I'm sorry I know this isn't an issue with the component as such and I don't know any other way to contact you guys, but I cannot find any licensing information.

I'd really like use this object, but without any licensing information I'd be violating your copyright if I distribute it along with my application.

My own project is AGPL licensed, so almost any open license will  work for me.

**Comment by jpillora** [comment]
https://github.com/jpillora/jquery.rest#mit-license MIT :)

**Comment by antoncl** [comment]
Thanks m8 ;-)
