### ISSUE TITLE
TypeError: $.RestClient is not a constructor

### ISSUE THREAD

**Issue by emreozen** [jpillora/jquery.rest#35]
Sorry I am a beginner with this but getting the TypeError: $.RestClient is not a constructor error in the console, when I do.

//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
/static/js/jquery.rest.js"></script> 

```
function getSQS(id, role )
{
   var client = new $.RestClient("/api/");
   client.add(role);
   client.add(id);
   var results = client.read()

   results.done(function (data){
       alert('Results: ' + data);
});

}
```

I would really appreciate the help. 

Thank you!

**Comment by jpillora** [comment]
That's strange, open http://jpillora.com/jquery.rest/examples/basic.html and open the console and try it. Works for me. What browser are you trying this in?

**Comment by emreozen** [comment]
Thanks for the response, it's on Firefox 32.0.3 on Mac. I ended up using raw jQuery.ajax. It's a shame, cause yours looks so much easier. :/

**Comment by jpillora** [comment]
this plugin is using jquery ajax underneath, so it should work, and i just tested it on mac FF 33, works. must be something wrong with your page
