### ISSUE TITLE
Type Error in .read() function

### ISSUE THREAD

**Issue by shandhiviyarajan** [jpillora/jquery.rest#37]
![screen shot 2015-01-02 at 2 34 50 pm](https://cloud.githubusercontent.com/assets/4089349/5594991/af795be4-928c-11e4-92d5-132c1f9ce541.png)

Can you explain why this issues i raising...

**Comment by jpillora** [comment]
very strange... can you make an online demo of it?

**Comment by shandhiviyarajan** [comment]
No problem i fixed it :)
