### ISSUE TITLE
 No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by shandhiviyarajan** [jpillora/jquery.rest#38]
![screen shot 2015-01-02 at 4 00 28 pm](https://cloud.githubusercontent.com/assets/4089349/5595444/9965a360-9298-11e4-8f97-2e231ed81582.png)

How to fix this issue?

**Comment by shandhiviyarajan** [comment]
$value = file_get_contents(url);
echo $value;

This is perfectly works ;)

**Comment by jpillora** [comment]
Not sure what that code does... `Access-Control-Allow-Origin` is a cross-domain error.

**Comment by shandhiviyarajan** [comment]
Yes but this PHP works here to get the JSON.

But still the JS issue is there :( 

$value = file_get_contents(url);
echo $value;

**Comment by jpillora** [comment]
Oh I see, you're performing the request on the server

**Comment by t2wu** [comment]
I ran into the same error. I tested the server with Chrome Postman it works, but using jquery.rest loaded from a static file (cross site) I ran into this same error.

**Comment by jpillora** [comment]
@t2wu read this article https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS - basically you cant send ajax requests to a different domain without altering the server headers (or using [xdomain](https://github.com/jpillora/xdomain))
