### ISSUE TITLE
Access to HTTP return codes

### ISSUE THREAD

**Issue by AleyCZ** [jpillora/jquery.rest#39]
One important part of working with REST services is the usage of HTTP return codes. I can't see anywhere in the documentation of jquery.rest where HTTP return code number is available. The done() handler has just one parameter - the HTTP response body. But where can I get the response code number? Please either add this important feature to the library, or document it properly if it is already present somewhere.

**Comment by jpillora** [comment]
HTTP **status** codes, and jquery.rest just uses plain `$.ajax`, so all the docs about `done()` can be found [on the jquery website](http://api.jquery.com/jquery.ajax/), though you're looking for this:

``` js
$.get("foo.html").done(function(data, textStatus, xhr) {
  console.log(xhr.status);
});
```
