### ISSUE TITLE
How to add Authorization token 

### ISSUE THREAD

**Issue by ZakariaJawas** [jpillora/jquery.rest#59]
is it possible to add a Bearer authorization token with the request ?

**Comment by jpillora** [comment]
https://github.com/jpillora/jquery.rest/blob/gh-pages/README.md#basic-authentication

**Comment by ZakariaJawas** [comment]
But the api i'm working on requires "Bearer token" not "Basic auth".
in the default JQuery ajax call i send it as a header 
{Authorization:  Bearer  + token}

**Comment by jpillora** [comment]
Oyea sorry you can use Ajax options
