### ISSUE TITLE
using `delete` as method name might cause trouble

### ISSUE THREAD

**Issue by gr2m** [jpillora/jquery.rest#9]
I remember that I run into a problem with some browser because I used `delete` as method name, which is a reserved word by JavaScript. That's why it's recommended to use `object['delete']()` instead of of `object.delete()`. That leads to an ugly API which is why most of the libraries and up to use an alternative, like `destroy()`, `remove()` or `del()`, what jquery.rest provides as well. I'd recommend to remove the `.delete()` method entirely.

I'm not sure what the state is with todays browsers, just wanted to make you aware that this might cause problems.

Besides that, great API to simplify a common problem, well done!

**Comment by jpillora** [comment]
Hi Gregor

Thanks for the heads up, just looked it up, yes it will fail in IE 6 7 8 it
seems, will change it to show an alert so no one uses it, just out at the
moment

And thanks, that's what I was going for :)
